### ISSUE TITLE
ForEach loop, change to any property of the element stops loop

### ISSUE THREAD

**Issue by igotbass** [ukandrewc/Webview2.Winforms.DOM#1]
Any changes to element, set attrib stops the loop from executing as if u did a break.

foreach (WVElement TheElement in webView21.Document.get_EvaluateAll("//*"))
            {
                if (TheElement.get_Attribute("id") == "user_username")
                {
                    TheElement.set_Attribute("value", "USERNAME");                    
                }

                if (TheElement.get_Attribute("id") == "submit")
                {
                    TheElement.Click();
                }
            }

**Comment by ukandrewc** [comment]
Not seeing that here, but have found some other issues that may be causing it.

**Comment by ukandrewc** [comment]
It's because the DOM has changed inside the loop, so it can't continue. At the moment you can only use **Evaluate** passively.
I've updated the class with **Document.GetElementsByTagname**, and you can use **Document.All**
I think it's worth changing the way Evaluate works, so it elements can be changed inside the loop.

**Comment by ukandrewc** [comment]
EvaluateAll has now been changed to a snapshot, so you can modify elements from it.
